M48
; DRILL file {KiCad 8.0.1} date 2024-04-11T07:46:34+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-11T07:46:34+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X93.0Y-75.0
X93.0Y-120.5
X133.5Y-75.0
X133.5Y-120.5
T2
X129.03Y-80.59
M30
